// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segfy.Domain;

namespace Segfy.Domain.Migrations
{
    [DbContext(typeof(SegfyContext))]
    [Migration("20190714153410_EFCoreCodeFirstSample.Models.SegfyContext")]
    partial class EFCoreCodeFirstSampleModelsSegfyContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Segfy.Domain.Entities.ApoliceAutomovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AutomovelId");

                    b.Property<int?>("SeguradoId");

                    b.Property<decimal>("ValorPremio");

                    b.Property<string>("numero");

                    b.HasKey("Id");

                    b.HasIndex("AutomovelId");

                    b.HasIndex("SeguradoId");

                    b.ToTable("ApoliceAutomovel");
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Automovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Placa");

                    b.HasKey("Id");

                    b.ToTable("Automovel");
                });

            modelBuilder.Entity("Segfy.Domain.Entities.Segurado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Documento");

                    b.HasKey("Id");

                    b.ToTable("Segurado");
                });

            modelBuilder.Entity("Segfy.Domain.Entities.ApoliceAutomovel", b =>
                {
                    b.HasOne("Segfy.Domain.Entities.Automovel", "Automovel")
                        .WithMany()
                        .HasForeignKey("AutomovelId");

                    b.HasOne("Segfy.Domain.Entities.Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoId");
                });
#pragma warning restore 612, 618
        }
    }
}
